### ISSUE TITLE
0 value bug

### ISSUE THREAD

**Issue by kevinhodges** [tkellen/node-remapped#2]
Hey, not sure if you're excepting pull requests on this but i'm using your solution (pretty much exactly what I was looking for so firstly thankyou for saving me the time) but found a bug and a tweak i'd like to make.

Bug:  when you have a key with 0 value, if there is a default set for that key, this will incorrectly get overwritten with the default.  In my branch (not submitted yet) i've tweaked that and the test cases to check for it.

Tweak:  I want to be able to pass no 'defaults' argument and have it delete keys where there's no value as 'undefined' is not valid JSON.

Let me know if you are interested and i'll push my code up.

Cheers,

Kevin

**Comment by knownasilya** [comment]
Should probably be closed, since #3 was merged

**Comment by tkellen** [comment]
Truth, thanks!

**Comment by knownasilya** [comment]
Probably need to release a patch version as well. 

P.S. I found this after I wrote https://github.com/knownasilya/parky

**Comment by tkellen** [comment]
Also done--didn't realize I hadn't pushed it.  Again, thanks for the heads up.
